I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scripts/fifth_day.rpy", line 409, in script
    show elly
Exception: Image 'elly' does not accept attributes 'say'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scripts/fifth_day.rpy", line 409, in script
    show elly
  File "C:\renpy-8.0.3-sdk\renpy\ast.py", line 921, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\renpy-8.0.3-sdk\renpy\exports.py", line 1373, in say
    who(what, *args, **kwargs)
  File "C:\renpy-8.0.3-sdk\renpy\character.py", line 1206, in __call__
    old_attr_state = self.handle_say_attributes(False, interact)
  File "C:\renpy-8.0.3-sdk\renpy\character.py", line 1041, in handle_say_attributes
    if self.resolve_say_attributes(predicting, temporary_attrs):
  File "C:\renpy-8.0.3-sdk\renpy\character.py", line 986, in resolve_say_attributes
    renpy.exports.show(show_image)
  File "C:\renpy-8.0.3-sdk\renpy\exports.py", line 686, in show
    if not base.find_target() and renpy.config.missing_show:
  File "C:\renpy-8.0.3-sdk\renpy\display\image.py", line 414, in find_target
    self.target = target._duplicate(a)
  File "C:\renpy-8.0.3-sdk\renpy\display\core.py", line 397, in _duplicate
    args.extraneous()
  File "C:\renpy-8.0.3-sdk\renpy\display\core.py", line 265, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'elly' does not accept attributes 'say'.

Windows-10-10.0.22000 AMD64
Ren'Py 8.0.3.22090809
DGame 1.0
Mon Dec 26 02:39:00 2022
