I'm sorry, but an uncaught exception occurred.

While running game code:
PermissionError: [WinError 32] Процесс не может получить доступ к файлу, так как этот файл занят другим процессом: 'C:\\DGame\\game\\saves\\persistent'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\renpy-8.0.3-sdk\renpy\bootstrap.py", line 277, in bootstrap
    renpy.main.main()
  File "C:\renpy-8.0.3-sdk\renpy\main.py", line 663, in main
    renpy.persistent.update(True)
  File "C:\renpy-8.0.3-sdk\renpy\persistent.py", line 397, in update
    save()
  File "C:\renpy-8.0.3-sdk\renpy\persistent.py", line 413, in save
    renpy.loadsave.location.save_persistent(data)
  File "C:\renpy-8.0.3-sdk\renpy\savelocation.py", line 494, in save_persistent
    l.save_persistent(data)
  File "C:\renpy-8.0.3-sdk\renpy\savelocation.py", line 349, in save_persistent
    safe_rename(fn_new, fn)
  File "C:\renpy-8.0.3-sdk\renpy\loadsave.py", line 286, in safe_rename
    os.unlink(new)
PermissionError: [WinError 32] Процесс не может получить доступ к файлу, так как этот файл занят другим процессом: 'C:\\DGame\\game\\saves\\persistent'

Windows-10-10.0.22000 AMD64
Ren'Py 8.0.3.22090809
DGame 1.0
Wed Nov 23 20:40:05 2022
